spring:
  datasource:
    url: jdbc:mysql://23.94.102.135:3306/se_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: se_db
    password: Cw4y42KKzWYWfaYA
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8181
